### ISSUE TITLE
workload_domain resource does not allow creation of domain with shared NSXT cluster

### ISSUE THREAD

**Issue by pradeep17j** [vmware/terraform-provider-vcf#178]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

workload domain can share a NSXT cluster with an existing domain in which can the spec should be able to take only vip_fqdn and nsxt license of an existing domain.

 

### Use Case(s)

Creation of workload domain with shared NSXT

### Potential Configuration

Creation of workload domain with shared NSXT

### References

When tried it fails with error

Error: Insufficient nsx_manager_node blocks
│
│   on main.tf line 222, in resource "vcf_domain" "workload_domain3":
│  222:   nsx_configuration {
│
│ At least 1 "nsx_manager_node" blocks are required.

**Comment by spacegospod** [comment]
Hey @pradeep17j AFAIK what you are asking for is officially supported by the domain manager UI.
On the other hand the docs for the API state otherwise. `nsxtManagerSpecs` is a required field https://developer.broadcom.com/xapis/vmware-cloud-foundation-api/latest/data-structures/NsxTSpec

If we go along with the assumption that the API documentation is incorrect I will have to patch the SDK before I can implement this.

Meanwhile if you have any additional information please share. For example - can the NSX manager from management domains be shared with workload domains? Or is there any limit on the number of nodes?

**Comment by spacegospod** [comment]
Alright, I figured it out.

It turns out that in order to reuse the NSX manager of another domain you simply have to populate its data in the input spec.
To be precise - you need to populate the vip, vipFQDN and the nsxtManagerSpec fields.

Closing this issue since the requested functionality is already supported by the provider.
